# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4feb9a36726821c2b84ba4ac11757747e7a2508fb7f2805da5c06b78ecac2e693adbe6e624119f510c5402ea4ae807265a2602664dd8b44c8c989bdb1e4073ae

test:
  secret_key_base: 32347e003628b5e5acee5abc8264df8aedb4aeb7c224757215ab87eda8490a185aba553c0fdd4433dc793fadd347575c2b2b030ce4ad832f42df0d9edff7d562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
